CREATE TABLE concert (
    id VARCHAR(255) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    type VARCHAR(255),
    imgUrl VARCHAR(255),
    date VARCHAR(255),
    venue VARCHAR(255),
    genre VARCHAR(255),
    rating VARCHAR(255),
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
